# Python base image
FROM python:3.11.5-slim

# Set the working directory
WORKDIR /app

RUN apt-get update && apt-get install -y git
# Copy the requirements file
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Run the Python script
CMD ["python", "PythonFilter.py"]
