# Node.js base image
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

RUN npm install -g typescript

RUN npm run build 
# Install TypeScript globally
# Copy the rest of the application code
COPY . .

# Compile TypeScript files
RUN tsc

# Expose the port the app runs on
EXPOSE 5000

# Run the application
CMD ["npm", "start"]
