# Node.js base image
FROM node:18

# Set the working directory
WORKDIR /app

RUN npm install -g typescript
# Copy package.json and package-lock.json
COPY NodeApp/package*.json ./

# Install Node.js dependencies
RUN npm install

COPY NodeApp .

RUN npm run build

# Expose the port the app runs on
EXPOSE 5000

# Run the application
CMD ["node", "dist/index.js"]  
